name: supanos-sports-bar
services:
- name: web
  source_dir: /
  github:
    repo: YOUR_GITHUB_USERNAME/YOUR_REPO_NAME
    branch: main
    deploy_on_push: true
  run_command: npm start
  build_command: npm install --include=dev && npm run build && ln -sf ../dist/public server/public
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: NODE_ENV
    value: production
  - key: DATABASE_URL
    value: ${db.DATABASE_URL}
  - key: SESSION_SECRET
    value: "super-secret-production-key-2025-coral-app"
  - key: PORT
    value: "8080"
  http_port: 8080

databases:
- name: db
  engine: PG
  version: "15"
  num_nodes: 1
  size: db-s-dev-database